insert into Band (bandid, name) values (1, 'AC/DC');
insert into Band (bandid, name) values (2, 'Metallica');
insert into Band (bandid, name) values (3, 'Judas Priest');
insert into Band (bandid, name) values (4, 'Kiss');
insert into Band (bandid, name) values (5, 'Scorpions');
insert into Band (bandid, name) values (6, 'Kobranocka');
insert into Band (bandid, name) values (7, 'Lady Pank');
insert into Band (bandid, name) values (8, 'Perfect');
insert into Band (bandid, name) values (9, 'Maanam');
insert into Band (bandid, name) values (10, 'Kult');
insert into Band (bandid, name) values (11, 'Slayer');
insert into Band (bandid, name) values (12, 'The Rolling Stones');
insert into Band (bandid, name) values (13, 'Nirvana');
insert into Band (bandid, name) values (14, 'The White Stripes');
insert into Band (bandid, name) values (15, 'Elektryczne Gitary');
insert into Band (bandid, name) values (16, 'Czerwone Gitary');
insert into Band (bandid, name) values (17, 'Róże Europy');
insert into Band (bandid, name) values (18, 'Linkin Park');
insert into Band (bandid, name) values (19, 'Green Day');
insert into Band (bandid, name) values (20, 'Bajm');
insert into Band (bandid, name) values (21, 'Golec uOrkiestra');
insert into Band (bandid, name) values (22, 'Zakopower');
insert into Band (bandid, name) values (23, 'Wilki');
insert into Band (bandid, name) values (24, 'Vox');
insert into Band (bandid, name) values (25, 'Brathanki');
insert into Band (bandid, name) values (26, 'Myslovitz');
insert into Band (bandid, name) values (27, 'Oddział zamknięty');
insert into Band (bandid, name) values (28, 'Kombii');
insert into Band (bandid, name) values (29, 'Skaldowie');
insert into Band (bandid, name) values (30, 'Dżem');
